//! Emits the parity grid the web page is built around: many option cases, each priced by
//! this host build, so the page can ask the deployed contract for the same number and
//! compare.
//!
//! The page must never compute a price in JavaScript. A second implementation in floating
//! point would contradict the only claim the project makes, so the host side of every
//! comparison is produced here, in Rust, and shipped as data.
//!
//! `scripts/gen_parity.sh` writes it into the web app.

use arbnum::D;
use arbpricing::{european, binomial, Kind, Market};

const SCALE: i128 = 1_000_000_000;
const RATE: i128 = 50_000_000; // 5%
const CARRY: i128 = 10_000_000; // 1%

fn spots() -> Vec<i128> {
    vec![25, 100, 250, 500].into_iter().map(|v| v * SCALE).collect()
}

fn strikes() -> Vec<i128> {
    vec![50, 100, 200, 240, 250, 300, 500].into_iter().map(|v| v * SCALE).collect()
}

/// Raw tenors must match exactly on both sides, so they are integers here rather than
/// computed from days in two languages.
fn tenors() -> Vec<(i128, &'static str)> {
    vec![
        (19_178_082, "7d"),
        (82_191_781, "30d"),
        (250_000_000, "3m"),
        (500_000_000, "6m"),
        (1_000_000_000, "1y"),
    ]
}

fn sigmas() -> Vec<(i128, &'static str)> {
    vec![
        (50_000_000, "5%"),
        (100_000_000, "10%"),
        (200_000_000, "20%"),
        (350_000_000, "35%"),
        (600_000_000, "60%"),
        (1_000_000_000, "100%"),
    ]
}

fn market(spot: i128, strike: i128, t: i128, sigma: i128) -> Market {
    Market {
        spot: D::from_raw(spot),
        strike: D::from_raw(strike),
        t: D::from_raw(t),
        sigma: D::from_raw(sigma),
        rate: D::from_raw(RATE),
        carry: D::from_raw(CARRY),
    }
}

fn main() {
    let spots = spots();
    let strikes = strikes();
    let tenors = tenors();
    let sigmas = sigmas();

    let mut european_rows: Vec<String> = Vec::new();
    for (si, &spot) in spots.iter().enumerate() {
        for (ki, &strike) in strikes.iter().enumerate() {
            for (ti, &(t, _)) in tenors.iter().enumerate() {
                for (vi, &(sigma, _)) in sigmas.iter().enumerate() {
                    for (pi, kind) in [Kind::Call, Kind::Put].into_iter().enumerate() {
                        let m = market(spot, strike, t, sigma);
                        match european(&m, kind) {
                            Ok(v) => european_rows
                                .push(format!("[{si},{ki},{ti},{vi},{pi},\"{}\"]", v.raw())),
                            // A case the engine refuses is omitted rather than shipped as
                            // a zero: the page simply will not offer it.
                            Err(_) => continue,
                        }
                    }
                }
            }
        }
    }

    // The lattice panel: one fixed selection, so the gas contrast between a closed form
    // and a 512-step tree is the story rather than the parameter space.
    let mut lattice_rows: Vec<String> = Vec::new();
    for &steps in &[256u32, 512] {
        for american in [false, true] {
            for (pi, kind) in [Kind::Call, Kind::Put].into_iter().enumerate() {
                let m = market(250 * SCALE, 240 * SCALE, 250_000_000, 350_000_000);
                if let Ok(v) = binomial(&m, kind, steps as usize, american) {
                    lattice_rows.push(format!(
                        "{{\"steps\":{steps},\"american\":{american},\"kind\":{pi},\"price\":\"{}\"}}",
                        v.raw()
                    ));
                }
            }
        }
    }

    println!("{{");
    println!("  \"note\": \"Generated by cargo run --release -p arbreport --example parity_grid. Host-side prices for the deployed contract to be checked against.\",");
    println!("  \"scale\": {SCALE},");
    println!("  \"rate\": {RATE},");
    println!("  \"carry\": {CARRY},");
    println!("  \"spots\": [{}],", spots.iter().map(|v| v.to_string()).collect::<Vec<_>>().join(","));
    println!("  \"strikes\": [{}],", strikes.iter().map(|v| v.to_string()).collect::<Vec<_>>().join(","));
    println!(
        "  \"tenors\": [{}],",
        tenors.iter().map(|(r, l)| format!("{{\"raw\":{r},\"label\":\"{l}\"}}")).collect::<Vec<_>>().join(",")
    );
    println!(
        "  \"sigmas\": [{}],",
        sigmas.iter().map(|(r, l)| format!("{{\"raw\":{r},\"label\":\"{l}\"}}")).collect::<Vec<_>>().join(",")
    );
    println!("  \"european\": [");
    println!("    {}", european_rows.join(",\n    "));
    println!("  ],");
    println!("  \"lattice\": [");
    println!("    {}", lattice_rows.join(",\n    "));
    println!("  ]");
    println!("}}");

    eprintln!("cases: {} european, {} lattice", european_rows.len(), lattice_rows.len());
}